In [1]:
import torch
import numpy as np 

## Torch Initialization

In [4]:
def get_info(_tensor):
    print(f"""
    shape: {_tensor.shape}
    value: \n{_tensor}
    dtype: {_tensor.dtype}
    device: {_tensor.device}
    auto_grad: {_tensor.requires_grad}
    size: {_tensor.size()}
    """)

In [37]:
my_tensor = torch.tensor([[1,2,3],[4, 5, 6]], dtype=torch.float32)
get_info(my_tensor)


    shape: torch.Size([2, 3])
    value: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([2, 3])
    


In [38]:
#empty tensor - random values
empty_tensor = torch.empty(size=(3,3))
get_info(empty_tensor)


    shape: torch.Size([3, 3])
    value: 
tensor([[4.3872e-38, 3.0722e-41, 5.1902e-38],
        [3.0722e-41, 4.4842e-44, 0.0000e+00],
        [6.7262e-44, 0.0000e+00, 5.1902e-38]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [53]:
#normal distribution using empty
emptyn_tensor = torch.empty(size=(1,5)).normal_(mean=0, std=1)
get_info(emptyn_tensor)


    shape: torch.Size([1, 5])
    value: 
tensor([[-0.3821,  2.6038, -0.6509,  0.1829, -1.3555]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([1, 5])
    


In [55]:
#uniform ditribution using empty
emptyu_tensor = torch.empty(size=(1, 5)).uniform_(0, 1)
get_info(emptyu_tensor)


    shape: torch.Size([1, 5])
    value: 
tensor([[0.3220, 0.5265, 0.4665, 0.9356, 0.0536]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([1, 5])
    


In [39]:
#zero tensors
zero_tensor = torch.zeros(3, 3)
get_info(zero_tensor)


    shape: torch.Size([3, 3])
    value: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [40]:
#random_init - random values b/w 0 and 1
rand_tensor = torch.rand((3, 3))
get_info(rand_tensor)


    shape: torch.Size([3, 3])
    value: 
tensor([[0.2436, 0.3273, 0.1941],
        [0.3314, 0.3811, 0.1376],
        [0.3301, 0.1354, 0.6729]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [41]:
#randon init - normalized data
randn_tensor = torch.randn((3 ,3))
get_info(randn_tensor)


    shape: torch.Size([3, 3])
    value: 
tensor([[ 0.3789, -1.4276,  1.0941],
        [ 0.1440,  0.2304, -0.1611],
        [ 0.0436,  0.0668, -1.3032]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [42]:
#ones 
ones_tensor = torch.ones((3, 3))
get_info(ones_tensor)


    shape: torch.Size([3, 3])
    value: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [43]:
#identity matrix
identity_tensor = torch.eye(5, 5)
get_info(identity_tensor)


    shape: torch.Size([5, 5])
    value: 
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([5, 5])
    


In [50]:
#values in range
range_tensor = torch.arange(start=0, end=4, step=1).view(2,-1)
get_info(range_tensor)


    shape: torch.Size([2, 2])
    value: 
tensor([[0, 1],
        [2, 3]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([2, 2])
    


In [52]:
#linespace
linespace_tensor = torch.linspace(start=1,end=10,steps=10)
get_info(linespace_tensor)


    shape: torch.Size([10])
    value: 
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([10])
    


In [57]:
#diagonal matrix
x = torch.diag(torch.ones(3)*5)
get_info(x)


    shape: torch.Size([3, 3])
    value: 
tensor([[5., 0., 0.],
        [0., 5., 0.],
        [0., 0., 5.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


## Converting Tensor types

In [64]:
_tensor = torch.arange(4)
get_info(_tensor)


    shape: torch.Size([4])
    value: 
tensor([0, 1, 2, 3])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [65]:
#int to bool
get_info(_tensor.bool())


    shape: torch.Size([4])
    value: 
tensor([False,  True,  True,  True])
    dtype: torch.bool
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [66]:
#int to short
get_info(_tensor.short())


    shape: torch.Size([4])
    value: 
tensor([0, 1, 2, 3], dtype=torch.int16)
    dtype: torch.int16
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [67]:
#int to long
get_info(_tensor.long())


    shape: torch.Size([4])
    value: 
tensor([0, 1, 2, 3])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [68]:
#int to float16
get_info(_tensor.half())


    shape: torch.Size([4])
    value: 
tensor([0., 1., 2., 3.], dtype=torch.float16)
    dtype: torch.float16
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [69]:
#int to float32
get_info(_tensor.float())


    shape: torch.Size([4])
    value: 
tensor([0., 1., 2., 3.])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [71]:
#int to float64
get_info(tensor.double())


    shape: torch.Size([4])
    value: 
tensor([0., 1., 2., 3.], dtype=torch.float64)
    dtype: torch.float64
    device: cpu
    auto_grad: False
    size: torch.Size([4])
    


In [73]:
#numpy to torch
np_array = np.zeros((5, 5))
tensor = torch.from_numpy(np_array)
get_info(tensor)


    shape: torch.Size([5, 5])
    value: 
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
    dtype: torch.float64
    device: cpu
    auto_grad: False
    size: torch.Size([5, 5])
    


In [74]:
#torch to numpy
np_back = tensor.numpy()
np_back

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Tensor Math

In [110]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
get_info(x), get_info(y)


    shape: torch.Size([3])
    value: 
tensor([1, 2, 3])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([3])
    

    shape: torch.Size([3])
    value: 
tensor([9, 8, 7])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([3])
    


(None, None)

In [77]:
#addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
get_info(z1)


    shape: torch.Size([1, 3])
    value: 
tensor([[10., 10., 10.]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [78]:
z2 = torch.add(x, y)
get_info(z2)


    shape: torch.Size([1, 3])
    value: 
tensor([[10, 10, 10]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [79]:
 z3 = x + y
 get_info(z3)


    shape: torch.Size([1, 3])
    value: 
tensor([[10, 10, 10]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [80]:
#subtraction
sub = x - y
get_info(sub)


    shape: torch.Size([1, 3])
    value: 
tensor([[-8, -6, -4]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [81]:
#division element wise
div = torch.true_divide(x , y)
get_info(div)


    shape: torch.Size([1, 3])
    value: 
tensor([[0.1111, 0.2500, 0.4286]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [82]:
#inplace operator "_" symbol or += 
t = torch.zeros(3)
t.add_(5)
get_info(t)


    shape: torch.Size([3])
    value: 
tensor([5., 5., 5.])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([3])
    


In [83]:
#exponentiation
z = x.pow(2)
get_info(z)


    shape: torch.Size([1, 3])
    value: 
tensor([[1, 4, 9]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [84]:
z = x ** 2
get_info(z)


    shape: torch.Size([1, 3])
    value: 
tensor([[1, 4, 9]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [85]:
#comparison
z = x > 0
get_info(z)


    shape: torch.Size([1, 3])
    value: 
tensor([[True, True, True]])
    dtype: torch.bool
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [86]:
#matrix multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1,x2) # (2 x 3)
get_info(x3)


    shape: torch.Size([2, 3])
    value: 
tensor([[0.7225, 1.1690, 1.4535],
        [1.1337, 1.9774, 2.1281]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([2, 3])
    


In [87]:
x3 = x1.mm(x2)
get_info(x3)


    shape: torch.Size([2, 3])
    value: 
tensor([[0.7225, 1.1690, 1.4535],
        [1.1337, 1.9774, 2.1281]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([2, 3])
    


In [94]:
#matrix exp
matrix_exp = torch.rand((5, 5))
get_info(matrix_exp)


    shape: torch.Size([5, 5])
    value: 
tensor([[0.0987, 0.5101, 0.2644, 0.1551, 0.6742],
        [0.6033, 0.4366, 0.9249, 0.7439, 0.6347],
        [0.0912, 0.1093, 0.3351, 0.9996, 0.5290],
        [0.3131, 0.5678, 0.7910, 0.9270, 0.8774],
        [0.4264, 0.8771, 0.4725, 0.4592, 0.1261]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([5, 5])
    


In [97]:
get_info(matrix_exp.matrix_power(3))


    shape: torch.Size([5, 5])
    value: 
tensor([[1.4213, 2.1770, 2.6661, 3.2385, 2.6942],
        [2.7432, 4.3375, 5.0298, 6.1056, 4.8273],
        [1.9162, 2.9822, 3.5307, 4.3001, 3.4099],
        [2.9800, 4.6801, 5.5266, 6.7417, 5.4092],
        [2.0043, 3.3032, 3.7049, 4.6386, 3.6532]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([5, 5])
    


In [101]:
#element wise multiplication
z = x * y 
get_info(z)


    shape: torch.Size([1, 3])
    value: 
tensor([[ 9, 16, 21]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([1, 3])
    


In [111]:
#dot product element wise + sum
z = x.dot(y)
get_info(z)


    shape: torch.Size([])
    value: 
46
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([])
    


In [119]:
#batch matrix mulitplication
batch = 32
n = 10
m = 20
p = 30
ten1 = torch.rand((batch, n, m))
ten2 = torch.rand((batch, m, p))

ten1.shape, ten2.shape

(torch.Size([32, 10, 20]), torch.Size([32, 20, 30]))

In [121]:
out_bmm = torch.bmm(ten1, ten2)
get_info(out_bmm)


    shape: torch.Size([32, 10, 30])
    value: 
tensor([[[4.2843, 3.4932, 4.2596,  ..., 4.3676, 3.0214, 4.6338],
         [6.0646, 5.7161, 5.9176,  ..., 6.1094, 4.9796, 6.5656],
         [4.7613, 5.3164, 4.8666,  ..., 5.5920, 3.2635, 5.5316],
         ...,
         [4.7804, 5.0209, 4.3004,  ..., 5.5910, 4.0651, 5.5603],
         [4.4642, 4.2086, 4.4825,  ..., 4.9740, 3.8879, 4.9063],
         [5.2720, 4.5789, 5.2932,  ..., 5.4711, 3.0460, 4.5582]],

        [[5.1765, 4.9433, 3.6854,  ..., 3.8314, 5.0445, 4.8270],
         [4.8715, 4.8692, 4.1334,  ..., 4.1084, 4.7327, 5.2793],
         [5.6576, 6.5847, 4.1105,  ..., 4.6973, 5.1221, 6.1996],
         ...,
         [4.6353, 5.7435, 3.9333,  ..., 3.6178, 4.3258, 5.1409],
         [5.5744, 5.3704, 3.2924,  ..., 4.0150, 4.8925, 4.9965],
         [4.9379, 5.2856, 2.7256,  ..., 3.8521, 4.2637, 5.2334]],

        [[6.1504, 6.0251, 4.6805,  ..., 6.5864, 5.6822, 5.7410],
         [4.1324, 4.3289, 3.8874,  ..., 5.2566, 4.7318, 4.2560],
         

In [122]:
#broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
x1, x2 

(tensor([[0.9191, 0.0504, 0.6903, 0.1190, 0.4860],
         [0.9161, 0.6592, 0.8321, 0.8903, 0.1048],
         [0.0150, 0.8253, 0.1072, 0.8821, 0.7110],
         [0.6549, 0.6091, 0.0230, 0.6032, 0.8856],
         [0.5755, 0.3795, 0.1057, 0.7136, 0.6593]]),
 tensor([[0.5006, 0.3530, 0.3741, 0.6056, 0.4413]]))

In [124]:
z = x1 - x2  # x2: (1 x 5) becomes (5 x 5) called broadcasting
get_info(z)


    shape: torch.Size([5, 5])
    value: 
tensor([[ 0.4185, -0.3026,  0.3162, -0.4866,  0.0448],
        [ 0.4155,  0.3062,  0.4580,  0.2847, -0.3365],
        [-0.4856,  0.4723, -0.2669,  0.2765,  0.2698],
        [ 0.1543,  0.2561, -0.3511, -0.0024,  0.4444],
        [ 0.0750,  0.0265, -0.2684,  0.1080,  0.2180]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([5, 5])
    


In [129]:
#other tensor operations
sum_x = torch.sum(x, dim=0)
sum_x

tensor(6)

In [145]:
#max
values, indices = torch.max(x, dim = 0)
values, indices

(tensor(3), tensor(2))

In [147]:
#min
values, indices = torch.min(x, dim = 0)
values, indices

(tensor(1), tensor(0))

In [148]:
#absolute value
abs_x = torch.abs(x)
abs_x

tensor([1, 2, 3])

In [149]:
#max index and min index
z_max = torch.argmax(x, dim=0)
z_min = torch.argmin(x, dim=0)
z_max, z_min

(tensor(2), tensor(0))

In [152]:
#mean 
mean_x = torch.mean(x.float(),dim=0)
get_info(mean_x)


    shape: torch.Size([])
    value: 
2.0
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([])
    


In [153]:
#element wise compare
z = torch.eq(x, y)
get_info(z)


    shape: torch.Size([3])
    value: 
tensor([False, False, False])
    dtype: torch.bool
    device: cpu
    auto_grad: False
    size: torch.Size([3])
    


In [160]:
#sort
sorted_y, indices = torch.sort(y, dim=0, descending=False)
sorted_y, indices

(tensor([7, 8, 9]), tensor([2, 1, 0]))

In [163]:
#clamp all elements less tha min are set to min and max than max are set to max
#exactly like a reLU
z = torch.clamp(x, min = 2, max = 10)
get_info(z)


    shape: torch.Size([3])
    value: 
tensor([2, 2, 3])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([3])
    


In [165]:
#any and all
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
z = torch.any(x) #any one should be true
z1 = torch.all(x) #all should be true
z, z1 

(tensor(True), tensor(False))

## Tensor Indexing

In [3]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))

In [7]:
x.shape

torch.Size([10, 25])

In [9]:
#first row of 25 features
print(x[0]), print(x[0,:])

tensor([0.6944, 0.5678, 0.0791, 0.3591, 0.1341, 0.6380, 0.9236, 0.2956, 0.4739,
        0.0236, 0.1732, 0.0945, 0.1069, 0.2041, 0.7743, 0.4053, 0.2558, 0.9041,
        0.5481, 0.7040, 0.0050, 0.8586, 0.9895, 0.9436, 0.3947])
tensor([0.6944, 0.5678, 0.0791, 0.3591, 0.1341, 0.6380, 0.9236, 0.2956, 0.4739,
        0.0236, 0.1732, 0.0945, 0.1069, 0.2041, 0.7743, 0.4053, 0.2558, 0.9041,
        0.5481, 0.7040, 0.0050, 0.8586, 0.9895, 0.9436, 0.3947])


(None, None)

In [11]:
#first features of all examples
x[:,0].shape, x[:,0]

(torch.Size([10]),
 tensor([0.6944, 0.0624, 0.5667, 0.9055, 0.7680, 0.2190, 0.0137, 0.4340, 0.6572,
         0.1467]))

In [15]:
# 10 features from the 3 examples
x[2,:10]

tensor([0.5667, 0.4363, 0.3621, 0.4054, 0.8850, 0.6946, 0.2370, 0.8312, 0.7059,
        0.1102])

In [16]:
#fancy indexing
x = torch.arange(10)
indices = [2, 5, 8]
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [17]:
print(x[indices])

tensor([2, 5, 8])


In [18]:
x = torch.rand((3 ,5))
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])

In [19]:
x 

tensor([[0.7608, 0.2645, 0.4885, 0.6603, 0.5071],
        [0.5064, 0.3102, 0.8241, 0.5841, 0.8356],
        [0.3864, 0.4779, 0.9628, 0.7651, 0.2878]])

In [20]:
print(x[rows, cols]) # ie x[1,4] and x[0,0]

tensor([0.8356, 0.7608])


In [35]:
#advanced indescing
x = torch.arange(10)
print(x[( x < 2 )|(x > 8)])

print(x[( x < 2 ) & (x > 8)])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)


In [30]:
print(x[x.remainder(2) == 0])

tensor([0, 2, 4, 6, 8])


In [31]:
#useful operations
print(torch.where(x > 5 ,x, x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [32]:
#unique tensors
x = torch.tensor([0,0,1,2,2,3,4])
print(x.unique())

tensor([0, 1, 2, 3, 4])


In [33]:
#num of dimension
print(x.ndimension())

1


In [39]:
#count of number of elements in tensor
x.numel()

10

## Tensor Dimensional reshape

In [40]:
#reshape using view
x = torch.arange(9)
x_3x3 = x.view(3, 3)
get_info(x_3x3)


    shape: torch.Size([3, 3])
    value: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [41]:
x_3x3 = x.reshape(3 ,3)
get_info(x_3x3)


    shape: torch.Size([3, 3])
    value: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
    dtype: torch.int64
    device: cpu
    auto_grad: False
    size: torch.Size([3, 3])
    


In [42]:
y = x_3x3.T
y

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [46]:
# view works on contiguose subspaces
# means further reshaping of tensor after view creates error
# where as reshape is totally fine with it
y.reshape(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [47]:
y.contiguous().view(9)

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [53]:
#combine two tensor
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

get_info(torch.cat((x1, x2),axis=0)) #axis 1 makes shape (2 x 10)


    shape: torch.Size([4, 5])
    value: 
tensor([[0.9382, 0.7948, 0.5082, 0.9726, 0.1131],
        [0.3795, 0.0300, 0.1513, 0.4929, 0.7871],
        [0.4515, 0.6074, 0.0228, 0.5144, 0.0087],
        [0.7184, 0.2213, 0.7019, 0.2749, 0.0713]])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([4, 5])
    


In [54]:
#flatten ie 2d to 1d
z = x1.view(-1)
get_info(z)


    shape: torch.Size([10])
    value: 
tensor([0.9382, 0.7948, 0.5082, 0.9726, 0.1131, 0.3795, 0.0300, 0.1513, 0.4929,
        0.7871])
    dtype: torch.float32
    device: cpu
    auto_grad: False
    size: torch.Size([10])
    


In [56]:
batch_size = 64
x = torch.rand((batch_size, 2, 5)) #(64 x 2 x 5)
#flatten it across 2 x 5 exculde batch_size

z = x.view(batch_size, -1)
z.shape

torch.Size([64, 10])

In [57]:
# switch axis
z = x.permute([0,2,1])
z.shape

torch.Size([64, 5, 2])

In [61]:
#unsqueeze or adding additional dimensions
x = torch.arange(10)
print(x.unsqueeze(axis=0).shape)
print(x.unsqueeze(axis=1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [63]:
x = torch.arange(10).unsqueeze(0).unsqueeze(0)
z = x.squeeze(0)
z.shape

torch.Size([1, 10])